In [1]:
import numpy as np

## Data types and Attributes

In [2]:
# Numpy's main datatype is ndarray
al = np.array([1, 2, 3, 4, 5])
al

array([1, 2, 3, 4, 5])

In [3]:
type(al)

numpy.ndarray

In [4]:
a2 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
a2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [5]:
a3 = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]]])
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [6]:
al.shape

(5,)

In [7]:
a2.shape

(2, 5)

In [8]:
a3.shape

(2, 3, 3)

In [9]:
al.ndim

1

In [10]:
a2.ndim

2

In [11]:
a3.ndim

3

In [12]:
al.dtype

dtype('int64')

In [13]:
al.size, a2.size, a3.size

(5, 10, 18)

In [14]:
type(al), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [15]:
# Create a dataframe from numpy array
import pandas as pd

df = pd.DataFrame(a2)

df

0  1  2  3   4
0  1  2  3  4   5
1  6  7  8  9  10

# 2. Creating arrays

In [16]:
# Create numpy arrays
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [17]:
sample_array.dtype

dtype('int64')

In [18]:
ones = np.ones((2, 3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [19]:
ones.dtype

dtype('float64')

In [20]:
type(ones)

numpy.ndarray

In [21]:
zeroes = np.zeros((2, 3))
zeroes

array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [25]:
random_array = np.random.randint(0, 10, size=(3, 5))
random_array

array([[9, 0, 9, 2, 6],
       [7, 8, 9, 2, 0],
       [2, 4, 1, 6, 6]])

In [26]:
random_array.size

15

In [27]:
random_array.shape

(3, 5)

In [32]:
random_array_2 = np.random.random((5, 3))
random_array_2

array([[0.98868428, 0.72489137, 0.42938439],
       [0.13079478, 0.33194733, 0.95406425],
       [0.35046805, 0.76740443, 0.70052736],
       [0.41322864, 0.20967061, 0.29008703],
       [0.34163195, 0.06321389, 0.24096479]])

In [31]:
random_array_2.shape

(5, 3)

In [33]:
random_array_3 = np.random.rand(5, 3)
random_array_3

array([[0.51046457, 0.45972223, 0.48040451],
       [0.93245265, 0.57943947, 0.96071971],
       [0.27250283, 0.48058841, 0.18770441],
       [0.88683836, 0.05795846, 0.80350021],
       [0.76730092, 0.38156152, 0.7639831 ]])