In [2]:
import numpy as np

## Data types and Attributes

In [3]:
# Numpy's main datatype is ndarray
al = np.array([1, 2, 3, 4, 5])
al

array([1, 2, 3, 4, 5])

In [4]:
type(al)

numpy.ndarray

In [5]:
a2 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
a2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [6]:
a3 = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]]])
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [7]:
al.shape

(5,)

In [8]:
a2.shape

(2, 5)

In [9]:
a3.shape

(2, 3, 3)

In [10]:
al.ndim

1

In [11]:
a2.ndim

2

In [12]:
a3.ndim

3

In [13]:
al.dtype

dtype('int64')

In [14]:
al.size, a2.size, a3.size

(5, 10, 18)

In [15]:
type(al), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [16]:
# Create a dataframe from numpy array
import pandas as pd

df = pd.DataFrame(a2)

df

0  1  2  3   4
0  1  2  3  4   5
1  6  7  8  9  10

# 2. Creating arrays

In [17]:
# Create numpy arrays
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [18]:
sample_array.dtype

dtype('int64')

In [19]:
ones = np.ones((2, 3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [20]:
ones.dtype

dtype('float64')

In [21]:
type(ones)

numpy.ndarray

In [22]:
zeroes = np.zeros((2, 3))
zeroes

array([[0., 0., 0.],
       [0., 0., 0.]])

In [23]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [24]:
random_array = np.random.randint(0, 10, size=(3, 5))
random_array

array([[6, 3, 3, 5, 0],
       [9, 8, 7, 9, 5],
       [0, 0, 9, 8, 7]])

In [25]:
random_array.size

15

In [26]:
random_array.shape

(3, 5)

In [27]:
random_array_2 = np.random.random((5, 3))
random_array_2

array([[0.89056612, 0.67488499, 0.66383244],
       [0.0219465 , 0.67898841, 0.04862003],
       [0.36479314, 0.10578195, 0.09740365],
       [0.71900001, 0.97662547, 0.27272232],
       [0.53403003, 0.2146338 , 0.59989069]])

In [28]:
random_array_2.shape

(5, 3)

In [29]:
random_array_3 = np.random.rand(5, 3)
random_array_3

array([[0.76052313, 0.61642643, 0.06672574],
       [0.0068954 , 0.14154163, 0.46199932],
       [0.81690506, 0.27923964, 0.23023046],
       [0.35695516, 0.71080617, 0.13138434],
       [0.55335666, 0.44978257, 0.33170046]])

In [30]:
# Pseudo-random numbers
np.random.seed(seed=0)

random_array_4 = np.random.randint(10, size=(5, 3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [31]:
random_array_4.shape

(5, 3)

In [32]:
np.random.seed(7)

random_array_5 = np.random.random((5, 3))
random_array_5


array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

## 3. Viewing arrays and matrices

In [33]:
np.unique(random_array_4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
al

array([1, 2, 3, 4, 5])

In [35]:
a2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [36]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [37]:
a3.shape

(2, 3, 3)

In [38]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
a3[0][0]

array([1, 2, 3])

In [40]:
a3[0][0][0]

1

In [41]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [42]:
a3[:2]

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [43]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [44]:
a3[:2, :2]

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[10, 11, 12],
        [13, 14, 15]]])

In [45]:
a4 = np.random.randint(10, size=(2, 3, 4, 5))
a4

array([[[[3, 5, 8, 8, 7],
         [5, 0, 0, 2, 8],
         [9, 6, 4, 9, 7],
         [3, 3, 8, 3, 0]],

        [[1, 0, 0, 6, 7],
         [7, 9, 3, 0, 7],
         [7, 7, 0, 5, 4],
         [3, 1, 3, 1, 3]],

        [[4, 3, 1, 9, 5],
         [9, 1, 2, 3, 2],
         [2, 5, 7, 3, 0],
         [9, 9, 3, 4, 5]]],


       [[[3, 0, 4, 8, 6],
         [7, 2, 7, 3, 8],
         [6, 6, 5, 6, 5],
         [7, 1, 5, 4, 4]],

        [[9, 9, 0, 6, 2],
         [6, 8, 2, 4, 1],
         [6, 1, 5, 1, 6],
         [9, 8, 6, 5, 9]],

        [[7, 5, 4, 9, 6],
         [8, 1, 5, 5, 8],
         [3, 7, 7, 9, 4],
         [7, 5, 9, 6, 2]]]])

In [46]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [47]:
a4[1][0][0][:4]

array([3, 0, 4, 8])

In [49]:
a4[:, :, : , :1]

array([[[[3],
         [5],
         [9],
         [3]],

        [[1],
         [7],
         [7],
         [3]],

        [[4],
         [9],
         [2],
         [9]]],


       [[[3],
         [7],
         [6],
         [7]],

        [[9],
         [6],
         [6],
         [9]],

        [[7],
         [8],
         [3],
         [7]]]])

## 4. Manipulating & comparing arrays

### Arithmetic

In [55]:
al

array([1, 2, 3, 4, 5])

In [56]:
ones = np.ones((5))
ones

array([1., 1., 1., 1., 1.])

In [57]:
al + ones

array([2., 3., 4., 5., 6.])

In [58]:
al - ones

array([0., 1., 2., 3., 4.])

In [59]:
al * ones

array([1., 2., 3., 4., 5.])

In [60]:
a2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [62]:
al

array([1, 2, 3, 4, 5])

In [63]:
al * a2

array([[ 1,  4,  9, 16, 25],
       [ 6, 14, 24, 36, 50]])

In [64]:
a2 * a2

array([[  1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100]])

In [65]:
a2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [66]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [68]:
a3 * a2

ValueError: operands could not be broadcast together with shapes (2,3,3) (2,5) 

In [69]:
a2[:, :3]

array([[1, 2, 3],
       [6, 7, 8]])

In [71]:
shaped_a2 = a2[:, :3]
shaped_a2

array([[1, 2, 3],
       [6, 7, 8]])

In [72]:
shaped_a2 * a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [73]:
a2 / ones

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.]])

In [74]:
a2 // ones

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.]])

In [75]:
a2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [76]:
a2 ** 2

array([[  1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100]])

In [77]:
np.square(a2)

array([[  1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100]])

In [79]:
np.add(al, ones)

array([2., 3., 4., 5., 6.])

In [80]:
al % 2

array([1, 0, 1, 0, 1])

In [81]:
np.exp(al)

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

In [82]:
np.log(al)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])